miner/config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :visitors do
    get 'simulate'
  end

  # resources :metrics_events
  post '/metrics_events', to: 'metrics_events#create'
  get '/metrics_events/names', to: 'metrics_events#names'

  get 'dashboard/index'
  get '/new_simulation', to: 'visitors#new_simulation'
  match '/about', to: 'application#about', via: :get
end

miner/app/models/event_hub_client.rb
class EventHubClient


  def self.register_event(attributes)
    puts "Wut?"
    originator_id = attributes[:originator_id]
    originator_type = attributes[:originator_type]
    event_name = attributes[:name]
    puts "Registering #{attributes}"
    MetricsEvent.create(originator_id: originator_id, originator_type: originator_type, name: event_name)
  rescue Exception => e
    puts "Perse #{e}"
  ensure
    send_new_rankings
  end

  def self.send_new_rankings
    puts "Sending new rankings"
    when_rankings_ready do |rankings|
      puts "Triggering to dashboard"
      SocketMessenger.send_rankings rankings
    end
  end

  def self.when_rankings_ready
    scores = Visitor.all.map { |v| {id: v.id, score: ranker.score(v.metrics_events.map(&:name))} }
    yield scores
  rescue Exception => e
    puts "Midagi on kannis #{e}"
  end

  def self.ranker
    if @ranking.blank?
      @ranking = Ranking::NaiveBayes.new
      train
    end

    @ranking
  end

  def self.train
    good_sequences = [
      %w(visit_payment_form select_phone_number visit_payment_form scroll read_contact_information),
      %w(select_phone_number click_link click_link visit_payment_form visit_payment_form),
      %w(select_phone_number scroll click_link visit_payment_form visit_payment_form),
      %w(visit_payment_form read_contact_information select_phone_number)
    ].each { |s|
      puts "Training good with #{s}"
      @ranking.train_good(s)
    }

    bad_sequences = [
      %w(random_stuff scroll random_stuff do_nothing_for_a_while),
      %w(scroll click_link random_stuff),
      %w(click_link click_link do_nothing_for_a_while),
      %w(random_stuff scroll do_nothing_for_a_while)
    ].each { |s|
      puts "Training bad with #{s}"
      @ranking.train_bad(s)
    }
  end
end

miner/app/models/metrics_event.rb
class MetricsEvent < ActiveRecord::Base
  belongs_to :originator, polymorphic: true
  validates_presence_of :originator
end

miner/app/models/socket_messenger.rb
class SocketMessenger
  SIMULATION = :simulation
  DASHBOARD = :dashboard

  def self.send_rankings(rankings)
    WebsocketRails[DASHBOARD].trigger 'new_rankings', rankings
  end

  def self.send_new_visitor(visitor)
    WebsocketRails[DASHBOARD].trigger 'new_visitor', visitor.as_json
  end
end

miner/app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_many :metrics_events, as: :originator, dependent: :destroy

  def rank
    if metrics_events.count > 0
      EventHubClient.ranker.score(metrics_events.map(&:name))
    else
      0
    end
  end

  def as_json(options={})
    super.merge(rank: rank, metrics_events: metrics_events.map(&:name))
  end
end

miner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

miner/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

miner/app/controllers/metrics_events_controller.rb
class MetricsEventsController < ApplicationController
  def create
    puts "Create new? #{params}"
    EventHubClient.register_event params
  end

  def names
    render json: Ranking::EVENTS
  end
end

miner/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @visitors = Visitor.all
    respond_to do |format|
      format.html
      format.json { render json: @visitors }
    end
  end

  def destroy
    visitor = Visitor.find(params[:id])
    respond_to do |format|
      if visitor.present?
        visitor.destroy()
        format.json { head :ok }
      else
        format.json { head :not_found }
      end
    end
  end

  def new_simulation
    visitor = Visitor.create!
    SocketMessenger.send_new_visitor(visitor)
    redirect_to visitor_simulate_path(visitor)
  end

  def show
    visitor = Visitor.find(params[:id])
    respond_to do |format|
      if visitor.present?
        format.json { render json: visitor}
      else
        format.json { head :not_found }
      end
    end
  end

  def simulate
    @visitor = Visitor.find(params[:visitor_id])
    cookies[:visitor_id] = @visitor.id
  end
end

miner/app/views/application/bootstrap_example_page.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    meta content="" name="description"
    meta content="" name="author"
    link href="../../assets/ico/favicon.ico" rel=("shortcut icon")
    title Theme Template for Bootstrap
    /! Bootstrap core CSS
    link href="../../dist/css/bootstrap.min.css" rel="stylesheet"
    /! Bootstrap theme
    link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet"
    /! Custom styles for this template
    link href="theme.css" rel="stylesheet"
  body role="document"
    /! Fixed navbar
    .navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"  Bootstrap theme
        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li.active
              a href="#"  Home
            li
              a href="#about"  About
            li
              a href="#contact"  Contact
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#"
                | Dropdown
                b.caret
              ul.dropdown-menu
                li
                  a href="#"  Action
                li
                  a href="#"  Another action
                li
                  a href="#"  Something else here
                li.divider
                li.dropdown-header Nav header
                li
                  a href="#"  Separated link
                li
                  a href="#"  One more separated link
        /! /.nav-collapse
    .container.theme-showcase role="main"
      /! Main jumbotron for a primary marketing message or call to action
      .jumbotron
        h1 Hello, world!
        p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
        p
          a.btn.btn-primary.btn-lg href="#" role="button"  Learn more &raquo;
      .page-header
        h1 Buttons
      p
        button.btn.btn-lg.btn-default type="button"  Default
        button.btn.btn-lg.btn-primary type="button"  Primary
        button.btn.btn-lg.btn-success type="button"  Success
        button.btn.btn-lg.btn-info type="button"  Info
        button.btn.btn-lg.btn-warning type="button"  Warning
        button.btn.btn-lg.btn-danger type="button"  Danger
        button.btn.btn-lg.btn-link type="button"  Link
      p
        button.btn.btn-default type="button"  Default
        button.btn.btn-primary type="button"  Primary
        button.btn.btn-success type="button"  Success
        button.btn.btn-info type="button"  Info
        button.btn.btn-warning type="button"  Warning
        button.btn.btn-danger type="button"  Danger
        button.btn.btn-link type="button"  Link
      p
        button.btn.btn-sm.btn-default type="button"  Default
        button.btn.btn-sm.btn-primary type="button"  Primary
        button.btn.btn-sm.btn-success type="button"  Success
        button.btn.btn-sm.btn-info type="button"  Info
        button.btn.btn-sm.btn-warning type="button"  Warning
        button.btn.btn-sm.btn-danger type="button"  Danger
        button.btn.btn-sm.btn-link type="button"  Link
      p
        button.btn.btn-xs.btn-default type="button"  Default
        button.btn.btn-xs.btn-primary type="button"  Primary
        button.btn.btn-xs.btn-success type="button"  Success
        button.btn.btn-xs.btn-info type="button"  Info
        button.btn.btn-xs.btn-warning type="button"  Warning
        button.btn.btn-xs.btn-danger type="button"  Danger
        button.btn.btn-xs.btn-link type="button"  Link
      .page-header
        h1 Thumbnails
      img.img-thumbnail alt=("A generic square placeholder image with a white border around it), making it resemble a photograph taken with an old instant camera" data-src="holder.js/200x200"
        .page-header
          h1 Dropdown menus
        .dropdown.theme-dropdown.clearfix
          a#dropdownMenu1.sr-only.dropdown-toggle data-toggle="dropdown" href="#" role="button"
            | Dropdown
            b.caret
          ul.dropdown-menu aria-labelledby="dropdownMenu1" role="menu"
            li.active role="presentation"
              a href="#" role="menuitem" tabindex="-1"  Action
            li role="presentation"
              a href="#" role="menuitem" tabindex="-1"  Another action
            li role="presentation"
              a href="#" role="menuitem" tabindex="-1"  Something else here
            li.divider role="presentation"
            li role="presentation"
              a href="#" role="menuitem" tabindex="-1"  Separated link
        .page-header
          h1 Navbars
        .navbar.navbar-default
          .container
            .navbar-header
              button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
                span.sr-only Toggle navigation
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand href="#"  Project name
            .navbar-collapse.collapse
              ul.nav.navbar-nav
                li.active
                  a href="#"  Home
                li
                  a href="#about"  About
                li
                  a href="#contact"  Contact
                li.dropdown
                  a.dropdown-toggle data-toggle="dropdown" href="#"
                    | Dropdown
                    b.caret
                  ul.dropdown-menu
                    li
                      a href="#"  Action
                    li
                      a href="#"  Another action
                    li
                      a href="#"  Something else here
                    li.divider
                    li.dropdown-header Nav header
                    li
                      a href="#"  Separated link
                    li
                      a href="#"  One more separated link
            /! /.nav-collapse
        .navbar.navbar-inverse
          .container
            .navbar-header
              button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
                span.sr-only Toggle navigation
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand href="#"  Project name
            .navbar-collapse.collapse
              ul.nav.navbar-nav
                li.active
                  a href="#"  Home
                li
                  a href="#about"  About
                li
                  a href="#contact"  Contact
                li.dropdown
                  a.dropdown-toggle data-toggle="dropdown" href="#"
                    | Dropdown
                    b.caret
                  ul.dropdown-menu
                    li
                      a href="#"  Action
                    li
                      a href="#"  Another action
                    li
                      a href="#"  Something else here
                    li.divider
                    li.dropdown-header Nav header
                    li
                      a href="#"  Separated link
                    li
                      a href="#"  One more separated link
            /! /.nav-collapse
        .page-header
          h1 Alerts
        .alert.alert-success
          strong Well done!
          | You successfully read this important alert message.
        .alert.alert-info
          strong Heads up!
          | This alert needs your attention, but it's not super important.
        .alert.alert-warning
          strong Warning!
          | Best check yo self, you're not looking too good.
        .alert.alert-danger
          strong Oh snap!
          | Change a few things up and try submitting again.
        .page-header
          h1 Progress bars
        .progress
          .progress-bar aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" style=("width: 60%;")
            span.sr-only 60% Complete
        .progress
          .progress-bar.progress-bar-success aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" style=("width: 40%")
            span.sr-only 40% Complete (success)
        .progress
          .progress-bar.progress-bar-info aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" style=("width: 20%")
            span.sr-only 20% Complete
        .progress
          .progress-bar.progress-bar-warning aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" style=("width: 60%")
            span.sr-only 60% Complete (warning)
        .progress
          .progress-bar.progress-bar-danger aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" style=("width: 80%")
            span.sr-only 80% Complete (danger)
        .progress
          .progress-bar.progress-bar-success style=("width: 35%")
            span.sr-only 35% Complete (success)
          .progress-bar.progress-bar-warning style=("width: 20%")
            span.sr-only 20% Complete (warning)
          .progress-bar.progress-bar-danger style=("width: 10%")
            span.sr-only 10% Complete (danger)
        .page-header
          h1 List groups
        .row
          .col-sm-4
            ul.list-group
              li.list-group-item Cras justo odio
              li.list-group-item Dapibus ac facilisis in
              li.list-group-item Morbi leo risus
              li.list-group-item Porta ac consectetur ac
              li.list-group-item Vestibulum at eros
          /! /.col-sm-4
          .col-sm-4
            .list-group
              a.list-group-item.active href="#"
                | Cras justo odio
              a.list-group-item href="#"  Dapibus ac facilisis in
              a.list-group-item href="#"  Morbi leo risus
              a.list-group-item href="#"  Porta ac consectetur ac
              a.list-group-item href="#"  Vestibulum at eros
          /! /.col-sm-4
          .col-sm-4
            .list-group
              a.list-group-item.active href="#"
                h4.list-group-item-heading List group item heading
                p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
              a.list-group-item href="#"
                h4.list-group-item-heading List group item heading
                p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
              a.list-group-item href="#"
                h4.list-group-item-heading List group item heading
                p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
          /! /.col-sm-4
        .page-header
          h1 Panels
        .row
          .col-sm-4
            .panel.panel-default
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
            .panel.panel-primary
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
          /! /.col-sm-4
          .col-sm-4
            .panel.panel-success
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
            .panel.panel-info
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
          /! /.col-sm-4
          .col-sm-4
            .panel.panel-warning
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
            .panel.panel-danger
              .panel-heading
                h3.panel-title Panel title
              .panel-body
                | Panel content
          /! /.col-sm-4
        .page-header
          h1 Wells
        .well
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.
    /! /container
    /!
      | Bootstrap core JavaScript
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    script src="../../dist/js/bootstrap.min.js"
    script src="../../assets/js/docs.min.js"

miner/app/views/dashboard/index.slim
coffee:
  startApp(Applications.LIVE_DISPLAY)

#main-region
  .visitors-list

miner/app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    title= "Visitor rank"
    meta name="description" content=""
    meta name="author" content=""
    meta name="keywords" content=""
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
    = javascript_include_tag "application"
  body role="document"
    = navbar fixed: :top, class: 'navbar-inverse' do
      = navbar_header brand: 'Visitor rank'
      = navbar_collapse do
        = navbar_group class: 'foo', id: 'menu' do
          = navbar_item 'Dashboard', dashboard_index_path
          = navbar_item 'Visitors', visitors_path
          - if @visitor.present?
            = navbar_item 'Simulate (new visitor)', visitor_simulate_path(@visitor)
          - else
            = navbar_item 'Simulate (new visitor)', new_simulation_path
          = navbar_item 'About', about_path
    .container
      = yield

miner/app/views/metrics_events/create.html.erb
<h1>MetricsEvents#create</h1>
<p>Find me in app/views/metrics_events/create.html.erb</p>

miner/app/views/visitors/index.slim
h1 Visitors#index

table.table.table-striped
  thead
    th #
    th Visitor name
    th Number of events
    th Rank (if were on the page)
    th Actions
  tbody
    - @visitors.each do |v|
      tr
        td= v.id
        td= v.name
        td= v.metrics_events.count
        td= v.rank
        td
          a href="#{visitor_simulate_path(v)}"
            .btn.btn-primary Simulate

miner/app/views/visitors/simulate.slim
coffee:
  startApp(Applications.SIMULATOR)

#main-region
  #event-buttons

miner/app/views/visitors/teach.slim
button.btn.btn-primary Start new lesson
p
button.btn.btn-success Mark as GOOD
p
button.btn.btn-warning Mark as BAD